version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672 #Interface
      - 5672:5672 #Rabbitmq
    volumes:
      - ./.data/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./.data/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      - boleto_team

networks:
  boleto_team:
    external:
      name: boleto_team
